### ISSUE TITLE
Inconsistent s-exp comment highlighting for Racket and student languages

### ISSUE THREAD

**Issue by sorawee** [racket/syntax-color#13]
```
#;(a b)

1

#;(a b)
```

is colored as shown here:

<img width="134" alt="Screen Shot 2022-09-04 at 3 21 20 PM" src="https://user-images.githubusercontent.com/9099577/188335640-2c1495e7-b8b1-4516-bb9d-0024efc51e93.png">

The first and second occurrence of `#;(a b)` are colored differently, which is very weird, especially when we are in student languages.

I suspect that this is because the syntax colorer for student languages is just the standard Racket's color lexer. But without the `#lang` line, it cannot find the relevant information to highlight correctly.

Note that the first occurrence is fully colored as a comment. This makes sense, because before `#lang` line, S-exp comment is colored like that too.

```
#;(a b)

#lang racket

#;(a b)
```

<img width="152" alt="Screen Shot 2022-09-04 at 3 26 38 PM" src="https://user-images.githubusercontent.com/9099577/188335774-d4e8d38d-61a2-4254-b277-d2adb68c7c7a.png">

**Comment by rfindler** [comment]
Looks like this was fixed for the `#lang` languages by [this commit](https://github.com/racket/syntax-color/commit/f3e7473d315c212a54fb9b2287a0d92040c3f033) and I'm seeing slightly different, but still wrong, behavior in the teaching languages:

<img width="981" alt="Screenshot 2023-02-22 at 2 16 52 PM" src="https://user-images.githubusercontent.com/399024/220749269-c6b886aa-d6e8-4725-91c9-bfd2d5099342.png">

but that might also be a problem with the [module lexer](https://github.com/racket/syntax-color/blob/master/syntax-color-lib/syntax-color/module-lexer.rkt), perhaps in the way that it is using (or not using) `racket-lexer*`.
